---
title: ScratchChat-filters
hero_image: images/banner.png
description: Voeg coole filters en afbeeldingen toe aan afbeeldingen van jezelf
version: 4
listed: false
copyedit: false
last_tested: "2020-04-01"
steps:
  - title: Inleiding
  - title: Zet het podium op
  - title: Hoe je van uiterlijk kunt wisselen
  - title: Meer uiterlijk mogelijkheden
  - title: Voeg een kleurenfilter toe
  - title: "Uitdaging: meer willekeur"
    challenge: true
  - title: Wat kun je verder nog doen?
