title: scratchchat-filters
hero_image: images/banner.png
description: scratchchat-filters description
version: 4
listed: false
copyedit: false
last_tested: "2020-04-01"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
