---
title: ScratchChat-Filter
hero_image: images/banner.png
description: Füge Bildern von dir coole Filter und Bilder hinzu
version: 4
listed: false
copyedit: false
last_tested: "2020-04-01"
steps:
  - 
    title: Einleitung
  - 
    title: Bühne einrichten
  - 
    title: Wie man Kostüme wechselt
  - 
    title: Mehr Kostümsteuerung
  - 
    title: Farbfilter hinzufügen
  - 
    title: "Herausforderung: Füge etwas zufällig hinzu"
    challenge: true
  - 
    title: Was kommt als Nächstes?
