---
title: Filtrele ScratchChat
hero_image: images/banner.png
description: Adaugă filtre și imagini cool la imaginile cu tine
version: 4
listed: false
copyedit: false
last_tested: "2020-04-01"
steps:
  - 
    title: Introducere
  - 
    title: Configurează scena
  - 
    title: Cum să schimbi costumele
  - 
    title: Mai multe controale pentru costume
  - 
    title: Adaugă un filtru pentru culoare
  - 
    title: "Provocare: adaugă mai multe posibilități"
    challenge: true
  - 
    title: Ce urmează?
