---
title: Filtros ScratchChat
hero_image: images/banner.png
description: Adicione filtros e imagens legais a suas próprias imagens
version: 4
listed: false
copyedit: false
last_tested: "2020-04-01"
steps:
  - title: Introdução
  - title: Preparar o palco
  - title: Como trocar de fantasias
  - title: Mais controles de fantasia
  - title: Adicionar um filtro de cores
  - title: "Desafio: Adicione alguma aleatoriedade"
  challenge: true
  - title: E agora?
