---
title: Filtres ScratchChat
hero_image: images/banner.png
description: Afegeix filtres i objectes interessants a la teva imatge
version: 4
listed: false
copyedit: false
last_tested: "2020-04-01"
steps:
  - 
    title: Introducció
  - 
    title: Configura l’escenari
  - 
    title: Com canviar els vestits
  - 
    title: Més controls del vestit
  - 
    title: Afegeix un filtre de color
  - 
    title: "Repte: Afegeix una mica d’atzar"
    challenge: true
  - 
    title: I ara què ve?
