---
title: ScratchChat濾鏡
hero_image: images/banner.png
description: 為自己的圖像添加漂亮的濾鏡和圖像
version: 4
listed: false
copyedit: false
last_tested: "2020-04-01"
steps:
  - 
    title: 介紹
  - 
    title: 創建背景
  - 
    title: 如何換造型
  - 
    title: 更多造型控制
  - 
    title: 添加顏色濾鏡
  - 
    title: "挑戰：增加一些隨機性"
    challenge: true
  - 
    title: 下一步是什麼？
