---
title: Filtros ScratchChat
hero_image: images/banner.png
description: Añade filtros e imágenes geniales a tus imágenes
version: 4
listed: false
copyedit: false
last_tested: '2020-04-01'
steps:
- title: Introducción
  completion: engaged
- title: Prepara el escenario
- title: Cómo cambiar disfraces
- title: Más controles para los disfraces
  completion: internal
- title: Añade un filtro de color
- title: 'Desafío: Añade aleatoriedad'
  challenge: true
- title: "¿Qué sigue?"
