---
title: Τα φίλτρα του ScratchChat
hero_image: images/banner.png
description: Πρόσθεσε απίθανα φίλτρα και εικόνες σε εικόνες του εαυτού σου
version: 4
listed: false
copyedit: false
last_tested: '2020-04-01'
steps:
- title: Εισαγωγή
  completion: engaged
- title: Ρύθμισε τη σκηνή
- title: Πώς να αλλάξεις ενδυμασία
- title: Περισσότερες ρυθμίσεις ενδυμασίας
  completion: internal
- title: Πρόσθεσε ένα φίλτρο χρώματος
- title: 'Πρόκληση: Πρόσθεσε κάποια τυχαιότητα'
  challenge: true
- title: Και τώρα;
