---
title: Filtres ScratchChat
hero_image: images/banner.png
description: Ajouter des filtres et des images sympas sur toi
version: 4
listed: false
copyedit: false
last_tested: '2020-04-01'
steps:
- title: Introduction
  completion: engaged
- title: Préparer la scène
- title: Comment changer de costume
- title: Plus de contrôles de costumes
  completion: internal
- title: Ajouter un filtre de couleur
- title: 'Défi: ajouter du hasard'
  challenge: true
- title: Et ensuite?
