---
title: Filtri ScratchChat
hero_image: images/banner.png
description: Aggiungi filtri ed immagini divertenti alle immagini di te stesso
version: 4
listed: false
copyedit: false
last_tested: '2020-04-01'
steps:
- title: Introduzione
  completion: engaged
- title: Prepara lo stage
- title: Come cambiare i costumi
- title: Più comandi sui costumi
  completion: internal
- title: Aggiungi un filtro colorato
- title: 'Sfida: Aggiungi un po'' di casualità'
  challenge: true
- title: E adesso?
